name: Main

on:
  pull_request:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

jobs:
  build-swig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Setup SWIG
        run: |
          git clone -b v8-isolate-aware-init https://github.com/dot-asm/swig;
          cd swig;
          ./autogen.sh;
          ./configure --prefix=$HOME/swig;
          make;
          make install;
      - name: Build bindings
        run: |
          export PATH=~/swig/bin:$PATH SWIG_LIB=~/swig/share/swig/4.1.0
          run.me
          ls -ltrh .
        working-directory: blst/bindings/python

      - name: Upload binding.python
        uses: actions/upload-artifact@v2
        with:
          name: blst_wrap.cpp
          path: blst/bindings/python/blst_wrap.cpp
          if-no-files-found: error
